
CREATE OR REPLACE PROCEDURE API_LF_REPORTS
(
    P_STUDENT_ID IN VARCHAR2,
    P_STUDENT_NAME IN VARCHAR2,
    P_PHONE_NUMBER IN VARCHAR2,
    P_ITEM_TYPE IN VARCHAR2,
    P_DESCRIPTION IN CLOB,
    P_LOCATION_LOST IN VARCHAR2
) AS
BEGIN
    INSERT INTO LF_REPORTS (STUDENT_ID, STUDENT_NAME, PHONE_NUMBER, ITEM_TYPE, DESCRIPTION, LOCATION_LOST)
    VALUES (P_STUDENT_ID, P_STUDENT_NAME, P_PHONE_NUMBER, P_ITEM_TYPE, P_DESCRIPTION, P_LOCATION_LOST);
END; 
/   


CREATE OR REPLACE PROCEDURE UPDATE_LOGIN_COUNT
(
    P_USERNAME VARCHAR2
)
IS
BEGIN

    UPDATE USERS
    SET LOGIN_COUNT = NVL(LOGIN_COUNT,0) + 1
    WHERE USER_NAME = P_USERNAME;

END;
/

CREATE OR REPLACE PROCEDURE SEND_LOGIN_OTP
(
    P_USERNAME VARCHAR2
)
IS
    V_OTP VARCHAR2(6);
    V_EMAIL VARCHAR2(100);
BEGIN

    V_OTP := TO_CHAR(TRUNC(DBMS_RANDOM.VALUE(100000,999999)));

    DELETE FROM ADMIN_OTP
    WHERE USER_NAME = P_USERNAME;

    INSERT INTO ADMIN_OTP
    VALUES
    (
        P_USERNAME,
        V_OTP,
        SYSTIMESTAMP + INTERVAL '5' MINUTE
    );

    SELECT EMAIL INTO V_EMAIL
    FROM VIEW_USERS  
    WHERE USER_NAME = P_USERNAME; 

    APEX_MAIL.SEND (
        p_to   =>  V_EMAIL,
        p_from => 'noreply@system.com',
        p_subj => 'Your login verification code',
        p_body => 'Your OTP code is: ' || V_OTP
    );

    APEX_MAIL.PUSH_QUEUE;

END;
/
