CREATE TABLE LF_REPORTS (
    REPORT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    STUDENT_ID VARCHAR2(50) NOT NULL,
    STUDENT_NAME VARCHAR2(200) NOT NULL,
    PHONE_NUMBER VARCHAR2(50),
    ITEM_TYPE VARCHAR2(100) NOT NULL,
    DESCRIPTION CLOB NOT NULL,
    LOCATION_LOST VARCHAR2(200),
    STATUS VARCHAR2(30),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);


CREATE OR REPLACE VIEW VIEW_CHART_LF_REPORTS AS
SELECT
    ITEM_TYPE,
    COUNT(*) AS REPORT_COUNT
FROM    
    LF_REPORTS
GROUP BY ITEM_TYPE;
/


CREATE TABLE LF_FOUND_ITEMS (
    ITEM_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ITEM_TYPE VARCHAR2(100) NOT NULL,
    DESCRIPTION CLOB NOT NULL,
    STORAGE_LOCATION VARCHAR2(200),
    IMAGE_FILE BLOB,
    IMAGE_MIME_TYPE VARCHAR2(100),
    IMAGE_FILENAME VARCHAR2(200),
    STATUS VARCHAR2(30),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);
/

CREATE OR REPLACE VIEW VIEW_CHART_LF_FOUND_ITEMS AS
SELECT 
    ITEM_TYPE,
    COUNT(*) AS FOUND_COUNT
FROM    
    LF_FOUND_ITEMS
GROUP BY ITEM_TYPE;
/


CREATE TABLE LF_MATCHES (
    MATCH_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    REPORT_ID NUMBER NOT NULL,
    ITEM_ID NUMBER NOT NULL,
    MATCH_STATUS VARCHAR2(30),
    VERIFIED_BY VARCHAR2(100),
    VERIFIED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    
    CONSTRAINT FK_MATCH_REPORT
        FOREIGN KEY (REPORT_ID)
        REFERENCES LF_REPORTS(REPORT_ID),

    CONSTRAINT FK_MATCH_ITEM
        FOREIGN KEY (ITEM_ID)
        REFERENCES LF_FOUND_ITEMS(ITEM_ID)
);
/

CREATE OR REPLACE VIEW VIEW_MATCHES AS
SELECT M.MATCH_ID, M.REPORT_ID, M.ITEM_ID, M.MATCH_STATUS, M.VERIFIED_BY, M.VERIFIED_AT, M.CREATED_AT,
       R.STUDENT_ID, R.STUDENT_NAME, R.PHONE_NUMBER, R.ITEM_TYPE, R.DESCRIPTION AS REPORT_DESCRIPTION, R.LOCATION_LOST,
       I.DESCRIPTION AS ITEM_DESCRIPTION, I.LOCATION_FOUND, I.FOUND_DATE
FROM LF_MATCHES M
JOIN LF_REPORTS R ON M.REPORT_ID = R.REPORT_ID
JOIN LF_FOUND_ITEMS I ON M.ITEM_ID = I.ITEM_ID;
/



CREATE TABLE LF_ACTIVITY_LOG (
    LOG_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME VARCHAR2(100),
    ACTION_TYPE VARCHAR2(200),
    EVENT_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);
/

CREATE TABLE USERS ( 
     USER_ID         GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
     USER_NAME       VARCHAR2 (50)  NOT NULL , 
     PASSWORD_HASH   VARCHAR2 (255)  NOT NULL , 
     ACTIVE_USER     NUMBER, 
     ROLE_TYPE       VARCHAR (30),
     PHONE_NUMBER    VARCHAR2(50),
     EMAIL           VARCHAR2(50),
     LOGIN_COUNT     NUMBER DEFAULT 0
);
/


CREATE OR REPLACE VIEW VIEW_USERS AS
SELECT USER_ID, USER_NAME, ACTIVE_USER, ROLE_TYPE, PHONE_NUMBER, EMAIL
FROM USERS
WHERE ACTIVE_USER = 1;
/


CREATE TABLE ADMIN_OTP (
    USER_NAME VARCHAR2(100),
    OTP_CODE VARCHAR2(10),
    EXPIRES_AT TIMESTAMP
);
/
